### ISSUE TITLE
[Feature] Add `GasFiller` example to `contracts` and as `gas_filler` example in `layers`

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#12]
Context: https://github.com/alloy-rs/examples/pull/8#discussion_r1526785851

~~Blocked by: https://github.com/alloy-rs/alloy/pull/326~~

~~This is now unblocked: https://github.com/alloy-rs/alloy/blob/main/crates/provider/src/layers/gas.rs~~

~~Blocked by: https://github.com/alloy-rs/alloy/issues/406~~

Now unblocked by https://github.com/alloy-rs/alloy/pull/426

**Comment by zerosnacks** [comment]
I'm running into some limitations around `CallBuilder` not supporting `(with)_chain_id()` as `GasLayer` defaulting to `EIP 1559` style transactions. It is also not clear if the nonce management takes contract deployments into account.

**Comment by DaniPopes** [comment]
wdym about CallBuilder? You can access the internal tx builder with `.map`
