### ISSUE TITLE
Add `debug_traceCallMany` + `trace_callMany` example

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#121]
See: https://github.com/alloy-rs/alloy/blob/135590eecfd82cf999d549e9440a70e370afe083/crates/provider/src/ext/trace.rs#L121-L126

For inspiration see: https://github.com/alloy-rs/examples/blob/main/examples/transactions/examples/trace_call.rs

**Comment by zerosnacks** [comment]
For reference see: https://github.com/alloy-rs/alloy/pull/1278

**Comment by codeWhizperer** [comment]
@zerosnacks I'd like to work on this. can I go ahead

**Comment by zerosnacks** [comment]
Hi @codeWhizperer 

Sure! Assigned to you

**Comment by codeWhizperer** [comment]
@zerosnacks I am done with the implementation, but I need to test it. I tried running `cargo run --examples trace_call.` I got the error: `Error: server returned an error response: error code -32603: method trace_call not supported`.

My question is, do I need to spin up anvil to test?

**Comment by zerosnacks** [comment]
Hi @codeWhizperer, that is expected behavior from public RPCs as simulation is quite a heavy RPC method usually reserved for non-free tiers.

I've made some small tweaks to your PR to use local Reth bindings which works :100:
