### ISSUE TITLE
Add GCP signer example

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#14]
See: https://github.com/alloy-rs/alloy/tree/main/crates/signer-gcp

**Comment by codeWhizperer** [comment]
@zerosnacks can I work on this?

**Comment by zerosnacks** [comment]
Sure! Assigned to you

**Comment by codeWhizperer** [comment]
<img width="2056" alt="Screenshot 2024-12-06 at 17 44 21" src="https://github.com/user-attachments/assets/8ec8eaa9-c12e-4847-b3ba-b48cca18c2b3">
@zerosnacks I have a question, signer-gcp doesn't seem to be exported from the signer crate unlike `aws`, `trezor` and `ledger`

**Comment by zerosnacks** [comment]
yes you can proceed with that @codeWhizperer, this is expected
