### ISSUE TITLE
Add example for comparing subscriptions from different providers

### ISSUE THREAD

**Issue by mattsse** [alloy-rs/examples#146]
similar to https://github.com/0xlosh/mempool-geth-vs-reth but should also showcase newHeads

## TODO
* add an example that checks receive timestamps of newHead subscriptions from two providers
* needs websocket transport
* spawn subscription and send timestamped responses to the main task where results from the providers are compared

**Comment by gakonst** [comment]
same thing for `eth_getBlock`!

woudl be great to also run this against two local nodes, but also against popular services like Alchemy, Infura etc -- including also our own Reth Public node's IP which we can provide.
