### ISSUE TITLE
[Chore] Update examples that use default Anvil + HTTP to `on_anvil` / `on_anvil_with_signer` 

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#63]
Already exposed through the `node_bindings` flag

We can use the `(provider, anvil) = ProviderBuilder::new().on_anvil();` syntax

Related: https://github.com/alloy-rs/alloy/issues/578

**Comment by zerosnacks** [comment]
@prestwich from the documentation it appears that this feature is specifically intended for tests. Just to be sure, this is not a pattern we would like to use in the examples, correct?

**Comment by prestwich** [comment]
note that after the `AnvilProvider` PR, the interface is now just `let provider = ProviderBuilder::default().on_anvil_with_signer()`
