### ISSUE TITLE
Add example showcasing `json` and `dyn` ABI encoding + `sol_types` static encoding

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#71]
https://github.com/alloy-rs/core/tree/main/crates/json-abi
https://github.com/alloy-rs/core/tree/main/crates/dyn-abi
https://docs.rs/alloy-sol-types/latest/alloy_sol_types/

**Comment by PraneshASP** [comment]
@zerosnacks I'd like to take this on. Do you have any suggestions for an optimal example for each type?

**Comment by zerosnacks** [comment]
> @zerosnacks I'd like to take this on. Do you have any suggestions for an optimal example for each type?

Thanks! The goal of the example is to clarify to users when you should use each type and how they are different from each other. For the vast majority of cases users should always use the `sol!` macro so this is an advanced use case. For inspiration have a look through the codebase of each crate. The result can be three different examples or just one example. A reference could be how we should different parts of working with big numbers: https://github.com/alloy-rs/examples/tree/main/examples/big-numbers/examples

**Comment by zerosnacks** [comment]
Hi @PraneshASP let me know if you are running into any issues or need any pointers

**Comment by PraneshASP** [comment]
Hi @zerosnacks sorry caught up with other things, I'm looking into adding examples now!

**Comment by zerosnacks** [comment]
No problem! Thanks

**Comment by PraneshASP** [comment]
Added example for `sol!()` macro as well. 

Example for `json` ABI encoding is left. It looks like there's no encode/decode method implemented in the[ json-abi](https://github.com/alloy-rs/core/tree/main/crates/json-abi) crate? `ethabi` [implements](https://docs.rs/ethabi/latest/ethabi/struct.Function.html#method.encode_input) it tho. Am I missing something?

cc: @zerosnacks

**Comment by zerosnacks** [comment]
I think ABI decoding should be sufficient here for the `json-abi` crate as shown here: https://github.com/alloy-rs/core/blob/main/crates/json-abi/tests/it/abis.rs

It would be nice to combine the various test cases into a single one covering the constructor, a function, an event and an error?
