### ISSUE TITLE
Add subscribe all contract events example

### ISSUE THREAD

**Issue by polipaul** [alloy-rs/examples#80]
Could you please add an example showing how to subscribe all contract events at once. Here is how it is possible with `ethers.rs`:

```rust
async fn listen_all_events(contract: &IERC20<Provider<Ws>>) -> Result<()> {
    let events = contract.events().from_block(16232696);
    let mut stream = events.stream().await?.take(1);

    while let Some(Ok(evt)) = stream.next().await {
        match evt {
            IERC20Events::ApprovalFilter(f) => println!("{f:?}"),
            IERC20Events::TransferFilter(f) => println!("{f:?}"),
        }
    }

    Ok(())
}

```

https://github.com/gakonst/ethers-rs/blob/51fe937f6515689b17a3a83b74a05984ad3a7f11/examples/contracts/examples/events.rs#L33-L52

**Comment by zerosnacks** [comment]
Hi @polipaul 

I've added this example: https://github.com/alloy-rs/examples/blob/example/subscribe-all-contract-events/examples/subscriptions/examples/subscribe_all_logs.rs

Would be great to hear if this resolves your request :)
