### ISSUE TITLE
Add example of using AnyNetwork type and populating customData in WithOtherFields

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/examples#85]
Relevant in the context of `op-alloy` and the requested usecase of ZKSync's Paymaster

Related: https://t.me/ethers_rs/38142

**Comment by alexfertel** [comment]
I had to do this today for Arbitrum receipts:

- Provider instantiation https://github.com/OpenZeppelin/rust-contracts-stylus/blob/6c2b511aa659e03f5c60cf41bc183b71529c43af/benches/src/erc20.rs#L48-L52
- Deserialization: https://github.com/OpenZeppelin/rust-contracts-stylus/blob/6c2b511aa659e03f5c60cf41bc183b71529c43af/benches/src/erc20.rs#L133

Let me know if it makes sense to convert this into an example.

**Comment by zerosnacks** [comment]
Hey @alexfertel, that would be great!
